name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    # run every 12 hours
    # - cron: "20 */12 * * *"
    # Every day at 5am
    - cron: "0 5 * * *"

permissions:
  contents: read

jobs:
  job1:
    name: Test Casks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-12, macos-11]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ivaquero/homebrew-chinese
          ref: main
          path: homebrew-chinese

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: true
          test-bot: false

      - name: Add Tap
        run: |
          brew tap ivaquero/chinese

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Bump casks
        uses: Homebrew/actions/bump-packages@master
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_CASK_REPO_WORKFLOW_TOKEN }}
          casks: ${{ github.event.inputs.casks || env.CASKS }}

      - name: Bumping Casks
        run: |
          brew install sd
          for cask in Casks/*.rb; do
            echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew bump-cask-pr
          done

  # job2:
  #   name: Test Formulae on Linux
  #   runs-on: ubuntu-20.04

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         repository: ivaquero/homebrew-chinese
  #         ref: main
  #         path: homebrew-chinese
  #     - name: Set up Homebrew
  #       uses: Homebrew/actions/setup-homebrew@master
  #       with:
  #         homebrew-version: "3.0.8"
  #         cache-version: v3
  #     - name: Install dependencies
  #       run: |
  #         brew tap ivaquero/chinese
  #         brew install ripgrep sd
  #     - name: Bump Formulae
  #       run: |
  #         for form in Formula/*.rb; do
  #             echo "ivaquero/chinese/$form" | sd "/Formula" "" | sd ".rb" "" | xargs brew bump-pr
  #         done
