name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job1:
    name: Test Casks A-F
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ivaquero/homebrew-chinese
          ref: main
          path: homebrew-chinese
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          homebrew-version: "3.0.8"
          cache-version: v3
      - name: Install dependencies
        run: |
          brew tap ivaquero/chinese
          brew install ripgrep sd
      - name: Test Casks
        run: |
          for cask in Casks/[a-f]*.rb; do
            echo $(basename $cask) | xargs brew livecheck --cask
          done

  job2:
    name: Test Formulae
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ivaquero/homebrew-chinese
          ref: main
          path: homebrew-chinese
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          homebrew-version: "3.0.8"
          cache-version: v3
      - name: Install dependencies
        run: |
          brew tap ivaquero/chinese
          brew install ripgrep sd
      - name: Test Formulae
        run: |
          for form in Formula/*.rb; do
              echo "ivaquero/chinese/$form" | sd "/Formula" "" | sd ".rb" "" | xargs brew install
          done

  job3:
    name: Test homebrew-chinese Formulae
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ivaquero/homebrew-chinese
          ref: main
          path: homebrew-chinese
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          homebrew-version: "3.0.8"
          cache-version: v3
      - name: Install dependencies
        run: |
          brew tap ivaquero/chinese
          brew install ripgrep sd
      - name: Test Formulae
        run: |
          for form in Formula/*.rb; do
              echo "ivaquero/chinese/$form" | sd "/Formula" "" | sd ".rb" "" | xargs brew install
          done
