name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Test homebrew-chinese A-F
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/chinese
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
          brew install ripgrep sd

          for cask in Casks/[a-f]*.rb; do
<<<<<<< HEAD
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew audit --cask --online
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew style --fix
||||||| 4cd065c
=======
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew style --fix
>>>>>>> f8c820d3c9472c4f1e344c080a7f4a589a6e9164
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew install
          done

  job2:
    name: Test homebrew-chinese G-N
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/chinese
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
          brew install ripgrep sd

          for cask in Casks/[g-n]*.rb; do
<<<<<<< HEAD
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew audit --cask --online
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew style --fix
||||||| 4cd065c
=======
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew style --fix
>>>>>>> f8c820d3c9472c4f1e344c080a7f4a589a6e9164
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew install
          done

  job3:
    name: Test homebrew-chinese O-T
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/chinese
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
          brew install ripgrep sd

          for cask in Casks/[o-t]*.rb; do
<<<<<<< HEAD
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew audit --cask --online
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew style --fix
||||||| 4cd065c
=======
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew style --fix
>>>>>>> f8c820d3c9472c4f1e344c080a7f4a589a6e9164
              echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew install
          done

  job4:
    name: Test homebrew-chinese formulae
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-10.15]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/chinese
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
          brew install ripgrep sd

          for formula in Formula/*.rb; do
              pkg=$(echo $formula | sd "Formula/" "" | sd ".rb" "")
              brew install $pkg
          done

  job5:
    name: Test homebrew-chinese formulae
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/chinese
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
          brew install ripgrep sd

          for formula in Formula/*.rb; do
              pkg=$(echo $formula | sd "Formula/" "" | sd ".rb" "")
              brew install $pkg
          done
