name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Test homebrew-chinese A-F
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ivaquero/homebrew-chinese
          ref: main
          path: homebrew-chinese
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          homebrew-version: "3.0.8"
          cache-version: v3
      - name: Install dependencies
        run: |
          brew tap ivaquero/chinese
          brew install ripgrep sd
      - name: Test Casks
        run: |
          for cask in Casks/[a-f]*.rb; do
            cask_name=$(basename "$cask" .rb)
            brew fetch --retry --force-bottle "ivaquero/chinese/$cask_name"
            brew livecheck --url="$cask_name" "ivaquero/chinese/$cask_name"
          done

  # job2:
  #   name: Test homebrew-chinese G-N
  #   runs-on: macos-11

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Homebrew
  #       id: set-up-homebrew
  #       uses: Homebrew/actions/setup-homebrew@master
  #     - name: Test script
  #       run: |
  #         brew tap ivaquero/chinese
  #         cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
  #         brew install ripgrep sd
  #         brew uninstall julia

  #         for cask in Casks/[g-n]*.rb; do
  #             # echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew livecheck
  #             echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew install
  #         done

  #   job3:
  #     name: Test homebrew-chinese O-T
  #     runs-on: macos-11

  #     steps:
  #       - uses: actions/checkout@v3
  #       - name: Set up Homebrew
  #         id: set-up-homebrew
  #         uses: Homebrew/actions/setup-homebrew@master
  #       - name: Test script
  #         run: |
  #           brew tap ivaquero/chinese
  #           cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
  #           brew install ripgrep sd

  #           for cask in Casks/[o-t]*.rb; do
  #               # echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew livecheck
  #               echo "ivaquero/chinese/$cask" | sd "/Casks" "" | sd ".rb" "" | xargs brew install
  #           done

  job2:
    name: Test homebrew-chinese Formulae
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/chinese
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
          brew install ripgrep sd

          for form in Formula/*.rb; do
              echo "ivaquero/chinese/$form" | sd "/Formula" "" | sd ".rb" "" | xargs brew install
          done

  job3:
    name: Test homebrew-chinese Formulae
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/chinese
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese
          brew install ripgrep sd

          for form in Formula/*.rb; do
              echo "ivaquero/chinese/$form" | sd "/Formula" "" | sd ".rb" "" | xargs brew install
          done
