name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Test homebrew-chinese on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Test script
        run: |
          brew tap ivaquero/chinese
          cd $(brew --prefix)/Homebrew/Library/Taps/ivaquero/homebrew-chinese

          if [[ $(uname -s) == "Darwin" ]]; then
              for cask in Casks/*.rb; do
                  echo "ivaquero/chinese/$cask" | sed "s/\/Casks//g" | sed "s/.rb//g" | xargs brew install
              done
          fi

          for formula in Formula/*.rb; do
              echo "ivaquero/chinese/$formula" | sed "s/\/Formula//g" | sed "s/.rb//g" | xargs brew install
          done
